homepage/urls.py
from django.urls import path
from . import views

app_name = 'Homepage'

urlpatterns = [
    path('', views.Homepage, name='Homepage'),
    path('About/', views.About, name='About'),
    path('Experience/', views.Experience, name='Experience'),
    path('Contact/', views.Contact, name='Contact'),
    path('Schedule/', views.Schedule, name='Schedule'),
    path('Schedule/<int:num>', views.Schedule_delete, name='Schedule_delete'),
]

story5/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, date

class add_schedule(models.Model):
    activity_name = models.CharField(max_length=100)
    category = models.CharField(max_length=100)
    place = models.CharField(max_length=100)
    time = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.activity_name

homepage/views.py
from django.shortcuts import render, redirect
from .models import add_schedule

def Homepage(request):
    return render(request, 'Homepage.html')

def About(request):
    return render(request, 'About.html')

def Experience(request):
    return render(request, 'Experience.html')

def Contact(request):
    return render(request, 'contact.html')

def Schedule(request):
    all_schedule=add_schedule.objects.all().order_by('time')
    context= {'all_schedule': all_schedule}
    if request.method == 'POST':
        schedule=add_schedule()
        schedule.activity_name= request.POST.get('activity_name')
        schedule.category= request.POST.get('category')
        schedule.place= request.POST.get('place')
        schedule.time= request.POST.get('time')
        schedule.save()
        return render(request, 'Schedule.html',context)
    else:
        return render(request, 'Schedule.html',context)
    

def Schedule_delete(request, num):
    obj = add_schedule.objects.all().order_by('time')
    obj_deleted = obj.get(id=num)
    obj_deleted.delete()
    return redirect('/Schedule/')

    

homepage/templates/About.html
{% load static %}
<html>
    <head>
        <title>Audrey Datau</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

         <!-- menghubungkan dengan css dan bootstrap -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="Stylesheet" href="{% static 'css/Story4.css' %}">

        <!-- membuat icon judul website-->
        <link rel="icon" href="{% static 'assets/logo.png' %}" type="image/icon">

        <!-- menggunakan jenis font yang sesuai -->
        <link href="https://fonts.googleapis.com/css?family=Mukta+Vaani&display=swap" rel="stylesheet">
    </head>

    <body>
        <!-- bagian navigasi yang paling atas dan terdapat logo paling kiri -->
        <div class="header">
            <nav class="navbar fixed-top navbar-light">
            <a class="navbar-brand" href="{% url 'Homepage:Homepage' %}">
            <img src="{% static 'assets/logo.png' %}" width="50" height="30" alt="">
            <a href="#" class="openButton" onclick="openNav()"><img src="{% static 'assets/nav.png' %}" width="50" height="50"></a>
            </a>
            </nav>        
        </div>

        <!-- mengatur hamburger navbar yang paling kanan -->
        <div id="nav" class="overlay">
            <a href="#" class="closeButton" onclick="closeNav()">X</a>
                <div class="overlay__content">
                    <a href="{% url 'Homepage:Homepage' %}" onclick="closeNav()">Home</a>
                    <a href="{% url 'Homepage:About' %}" onclick="closeNav()">About</a>
                    <a href="{% url 'Homepage:Experience' %}" onclick="closeNav()">Experience</a>
                    <a href="{% url 'Homepage:Contact' %}" onclick="closeNav()">Contact</a>
                    <a href="{% url 'Homepage:Schedule' %}" onclick="closeNav()">Schedule</a>
                </div>
        </div>

        <!-- bagian about     -->
        <div class="container-fluid" id="About">
            <div class="row">
                <div class="col-lg-4">
                    <h1>ABOUT</h1>
                    <img src="{% static 'assets/myphoto1.jpg' %}"  class="rounded-lg float-left">
                </div>
                <div class="col-lg-6">
                       <p>My name is Audrey Annisa Datau and you can call me 
                            Audrey. I was born and grew up in Jakarta, Indonesia.<br>
                            <br> I am a hardworking and punctual individual with passion
                            for technology. I work well in team and also on my own. 
                            I am well organized and love to make plans about things 
                            that i will do.

                       </p> 
                </div>
            </div>
        </div>

        <!-- menghubungkan dengan file javascript -->
        <script src="{% static 'js/Story4.js' %}"> </script>

    </body>
</html>

homepage/templates/Experience.html
{% load static %}
<html>
    <head>
        <title>Audrey Datau</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

         <!-- menghubungkan dengan css dan bootstrap -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="Stylesheet" href="{% static 'css/Story4.css' %}">

        <!-- membuat icon judul website-->
        <link rel="icon" href="{% static 'assets/logo.png' %}" type="image/icon">

        <!-- menggunakan jenis font yang sesuai -->
        <link href="https://fonts.googleapis.com/css?family=Mukta+Vaani&display=swap" rel="stylesheet">
    </head>

    <body>
        <!-- bagian navigasi yang paling atas dan terdapat logo paling kiri -->
        <div class="header">
            <nav class="navbar fixed-top navbar-light">
            <a class="navbar-brand" href="{% url 'Homepage:Homepage' %}">
                <img src="{% static 'assets/logo.png' %}" width="50" height="30" alt="">
            </a>
            <a href="#" class="openButton" onclick="openNav()"><img src="{% static 'assets/nav.png' %}" width="50" height="50"></a>
            </nav>        
        </div>

        <!-- mengatur hamburger navbar yang paling kanan -->
        <div id="nav" class="overlay">
            <a href="#" class="closeButton" onclick="closeNav()">X</a>
                <div class="overlay__content">
                    <a href="{% url 'Homepage:Homepage' %}" onclick="closeNav()">Home</a>
                    <a href="{% url 'Homepage:About' %}" onclick="closeNav()">About</a>
                    <a href="{% url 'Homepage:Experience' %}" onclick="closeNav()">Experience</a>
                    <a href="{% url 'Homepage:Contact' %}" onclick="closeNav()">Contact</a>
                    <a href="{% url 'Homepage:Schedule' %}" onclick="closeNav()">Schedule</a>
                </div>
        </div>

         <!-- bagian Experience -->
         <div class="AllExperience"  id="Experience">
            <h1>EXPERIENCE</h1>
            <div class="contentexperience">

            <div class="Experience1">
                    <p class="label success new-label">
                    <h3 class="align">Universitas Indonesia <h4><i>September 2019 - December 2019</i> </h4>  </h3> 
                    <h3 class="add-label"><strong>Universitas Indonesia 
                    <br> Teaching Assistant for Programming Foundation 1 </strong>
                    <br> Help and make students comfortable with programming, arranging tutorial problems, scoring students tutorial and assignments.
                    </h3></p>
            </div>
            
            <div class="Experience2">
                    <p class="label success new-label">
                    <h3 class="align">BEM FASILKOM UI <h4><i>February 2019 - December 2019 </i> </h4>  </h3> 
                    <h3 class="add-label"><strong>BEM FASILKOM UI 
                    <br> Public Relations Staff </strong>
                    <br> Maintain the publication of BEM Fasilkom UI in social media  and be a liason between
                    <br> BEM & external parties both inside and outside faculty.
                    </h3></p>
            </div>

            <div class="Experience3">
                    <p class="label success new-label">
                    <h3 class="align">COMPFEST <h4><i> March 2019 - September 2019 </i> </h4>   </h3>
                    <h3 class="add-label"> <strong>COMPFEST
                    <br> Marketing Staff</strong>
                    <br> Maintain all social media of COMPFEST.
                    </h3></p>
            </div>

            <div class="Experience4">
                    <p class="label success new-label">
                    <h3 class="align">CROPS PATRIOTS <h4><i> April 2017 </i> </h4>   </h3>
                    <h3 class="add-label"><strong>CROPS PATRIOTS
                    <br> Vice Project Officer</strong>
                    <br> Be the right handman for the project officer.
                    </h3></p>
            </div>
            
        </div>
    </div>
    


        <!-- menghubungkan dengan file javascript -->
        <script src="{% static 'js/Story4.js' %}"> </script>
  
    </body>
</html>

homepage/templates/Homepage.html
{% load static %}
<html>
    <head>
        <title>Audrey Datau</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

         <!-- menghubungkan dengan css dan bootstrap -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="Stylesheet" href="{% static 'css/Story4.css' %}">

        <!-- membuat icon judul website-->
        <link rel="icon" href="{% static 'assets/logo.png' %}" type="image/icon">

        <!-- menggunakan jenis font yang sesuai -->
        <link href="https://fonts.googleapis.com/css?family=Mukta+Vaani&display=swap" rel="stylesheet">
    </head>

    <body>
        <!-- bagian navigasi yang paling atas dan terdapat logo paling kiri -->
        <div class="header">
            <nav class="navbar fixed-top navbar-light">
            <a class="navbar-brand" href="{% url 'Homepage:Homepage' %}">
            <img src="{% static 'assets/logo.png' %}" width="50" height="30" alt="">
            </a>
            <a href="#" class="openButton" onclick="openNav()"><img src="{% static 'assets/nav.png' %}" width="50" height="50"></a>
            </nav>      
        </div>

        <!-- mengatur hamburger navbar yang paling kanan -->
        <div id="nav" class="overlay">
            <a href="#" class="closeButton" onclick="closeNav()">X</a>
                <div class="overlay__content">
                    <a href="{% url 'Homepage:Homepage' %}" onclick="closeNav()">Home</a>
                    <a href="{% url 'Homepage:About' %}" onclick="closeNav()">About</a>
                    <a href="{% url 'Homepage:Experience' %}" onclick="closeNav()">Experience</a>
                    <a href="{% url 'Homepage:Contact' %}" onclick="closeNav()">Contact</a>
                    <a href="{% url 'Homepage:Schedule' %}" onclick="closeNav()">Schedule</a>
                </div>
        </div>

        <!-- bagian landing page awal -->
        <section id="Home">
            <br>
            <br>
            <h1>HELLO, I'M</h1>
            <h2>AUDREY ANNISA DATAU!</h2>
            <h3>2nd year information system student</h3>
            <a class="btn btn-outline-dark btn-lg" href="{% url 'Homepage:About' %}">More</a>
        </section>

        
        <!-- menghubungkan dengan file javascript -->
        <script src="{% static 'js/Story4.js' %}"> </script>
    </body>
</html>

 <!-- credit to : freepik.com  -->

homepage/templates/Schedule.html
{% load static %}
<html>
    <head>
        <title>Audrey Datau</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <!-- menambahkan icon -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

         <!-- menghubungkan dengan css dan bootstrap -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="Stylesheet" href="{% static 'css/Story4.css' %}">

        <!-- membuat icon judul website-->
        <link rel="icon" href="{% static 'assets/logo.png' %}" type="image/icon">

        <!-- menggunakan jenis font yang sesuai -->
        <link href="https://fonts.googleapis.com/css?family=Mukta+Vaani&display=swap" rel="stylesheet">
    </head>

<body>
    <!-- bagian navigasi yang paling atas dan terdapat logo paling kiri -->
    <div class="header">
        <nav class="navbar fixed-top navbar-light">
        <a class="navbar-brand" href="{% url 'Homepage:Homepage' %}">
        <img src="{% static 'assets/logo.png' %}" width="50" height="30" alt="">
        </a>
        <a href="#" class="openButton" onclick="openNav()"><img src="{% static 'assets/nav.png' %}" width="50" height="50"></a>
        </nav>      
    </div>

    <!-- mengatur hamburger navbar yang paling kanan -->
    <div id="nav" class="overlay">
        <a href="#" class="closeButton" onclick="closeNav()">X</a>
        <div class="overlay__content">
            <a href="{% url 'Homepage:Homepage' %}" onclick="closeNav()">Home</a>
            <a href="{% url 'Homepage:About' %}" onclick="closeNav()">About</a>
            <a href="{% url 'Homepage:Experience' %}" onclick="closeNav()">Experience</a>
            <a href="{% url 'Homepage:Contact' %}" onclick="closeNav()">Contact</a>
            <a href="{% url 'Homepage:Schedule' %}" onclick="closeNav()">Schedule</a> 
            </div>
    </div>

    <div class="allcontent">
    <div class="AllSchedule" id="Schedule">
        <form method="POST" class="form">
            {% csrf_token %}
            <div class="form-group">
              <label for="activity_name" class="labelactivity">Activity: </label>
              <input type="text" class="form-control" id="activity_name" placeholder="" name="activity_name">
            </div>
            <div class="form-group">
              <label for="category" class="labelcategory">Category: </label>
              <input type="text" class="form-control" id="category" placeholder="" name="category">
            </div>
            <div class="form-group">
                    <label for="place" class="labelplace">place: </label>
                    <input type="text" class="form-control" id="place" placeholder="" name="place">
            </div>
            
            
            <div class="well">
                <div id="datetimepicker4" class="input-append">
                      <label for="time" class="labeldate">Date & Time: </label>
                      <input id="time" type="datetime-local" name="time">
                      <span class="add-on">
                      <i data-time-icon="icon-time" data-date-icon="icon-calendar">
                      </i>
                    </span>
                </div>
            </div>
                 
            <button type="submit" class="btn btn-primary">Submit</button>
            

        </form>
    </div>

    <div class="table_data" id="table_data">
    <h2>Schedule</h2>
    <br>
    <table class="table table-hover" id="table">
            <thead>
              <tr>
                <th scope="col">Date/time</th>
                <th scope="col">Activity</th>
                <th scope="col">Category</th>
                <th scope="col">Place</th>
              </tr>
            </thead>
            <div class="contentschedule">
            <tbody>
              {% for schedule in all_schedule %}
              <tr>
                <th scope="row">{{ schedule.time }}</th>
                <td>{{ schedule.activity_name }}</td>
                <td>{{ schedule.category }}</td>
                <td>{{ schedule.place }}</td>
                <td>
                <form method="POST" action="{% url 'Homepage:Schedule_delete' schedule.id %}">
                    {% csrf_token %}
                    <button class="btn btn-outline-dark btn-lg" type="submit" width="10px"><i class="fa fa-trash"></i></button>
                </form>
            </td>
              </tr>
              {% endfor %}
            </tbody>
            </div>
    </table>
    </div>
    </div>

        <script src="{% static 'js/Story4.js' %}" type="text/javascript"> 
        </script>
</body>

</html>

homepage/templates/contact.html
{% load static %}
<html>
    <head>
        <title>Audrey Datau</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

         <!-- menghubungkan dengan css dan bootstrap -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="Stylesheet" href="{% static 'css/Story4.css' %}">

        <!-- membuat icon judul website-->
        <link rel="icon" href="{% static 'assets/logo.png' %}" type="image/icon">

        <!-- menggunakan jenis font yang sesuai -->
        <link href="https://fonts.googleapis.com/css?family=Mukta+Vaani&display=swap" rel="stylesheet">
    </head>

    <body>
        <!-- bagian navigasi yang paling atas dan terdapat logo paling kiri -->
        <div class="header">
            <nav class="navbar fixed-top navbar-light">
            <a class="navbar-brand" href="{% url 'Homepage:Homepage' %}">
            <img src="{% static 'assets/logo.png' %}" width="50" height="30" alt="">
            </a>
            <a href="#" class="openButton" onclick="openNav()"><img src="{% static 'assets/nav.png' %}" width="50" height="50"></a>
            </nav>        
        </div>

        <!-- mengatur hamburger navbar yang paling kanan -->
        <div id="nav" class="overlay">
            <a href="#" class="closeButton" onclick="closeNav()">X</a>
            <div class="overlay__content">
                <a href="{% url 'Homepage:Homepage' %}" onclick="closeNav()">Home</a>
                <a href="{% url 'Homepage:About' %}" onclick="closeNav()">About</a>
                <a href="{% url 'Homepage:Experience' %}" onclick="closeNav()">Experience</a>
                <a href="{% url 'Homepage:Contact' %}" onclick="closeNav()">Contact</a>
                <a href="{% url 'Homepage:Schedule' %}" onclick="closeNav()">Schedule</a>
                </div>
        </div>

        <!-- bagian contact/get in touch -->
        <section id="contact">
            <br>
            <br>
            <h2>Get in Touch</h2>
            <h3> You can reach me through:</h3>
            <div class="button_cont" align="center">
                <a class="Email" href="mailto:audreydatau@gmail.com" target="_blank" rel="nofollow noopener">email</a>
                <a class="LinkedIn" href="https://www.linkedin.com/in/audrey-datau/" target="_blank" rel="nofollow noopener">LinkedIn</a>
                <a class="Instagram" href="https://www.instagram.com/audreydatau/" target="_blank" rel="nofollow noopener">Instagram</a>
            </div>
        </section>


        <!-- menghubungkan dengan file javascript -->
        <script src="{% static 'js/Story4.js' %}"> </script>
    </body>
</html>

<!--  credit to : freepik.com  -->